name: sci_tally_tool
version: 1.0.0
publish_to: none
source: lib

environment:
  sdk: '>1.20.1 <2.0.0'

dependencies:
  logging: any
  intl: "^0.15.2"
  http: "^0.11.3+16"
  json_annotation: ^0.2.2
  dson:
    git:
      url: git://github.com/nozzlegear/dson.git
      ref: c91a77acd60851

dev_dependencies:
  build_runner: ^0.6.1
  json_serializable: ^0.3.0